plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/entreprneuros/Library/CloudStorage/OneDrive-SharedLibraries-HowardUniversity/Faculty Corner HUCM - OFD Impact Dashboard/OFD/Examples Impact Dashboard Demo"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]