#!/usr/bin/env python3
"""
HUCM OFD Impact Dashboard — Auto-Update Script
===============================================
Drop updated files into this folder, then run this script
to regenerate hucm_ofd_dashboard.html.

Two update modes:
  1. Fast rebuild  — you already have a new final_payload.json
                     (e.g. generated by Claude or another tool)
  2. Full rebuild  — you have a new all_final.pkl from the data pipeline

Usage:
    python3 update_dashboard.py

Output:
    hucm_ofd_dashboard.html  (in the same folder)
"""

import json
import os
import sys
from datetime import datetime

FOLDER   = os.path.dirname(os.path.abspath(__file__))
PAYLOAD  = os.path.join(FOLDER, "final_payload.json")
TEMPLATE = os.path.join(FOLDER, "dashboard_template.html")
OUTPUT   = os.path.join(FOLDER, "hucm_ofd_dashboard.html")

print("=" * 55)
print("  HUCM OFD Impact Dashboard — Rebuild")
print("=" * 55)

# ── Check required files ────────────────────────────────────
for f, label in [(PAYLOAD, "final_payload.json"), (TEMPLATE, "dashboard_template.html")]:
    if not os.path.exists(f):
        print(f"\n❌  Missing: {label}")
        print(f"    Expected at: {f}")
        sys.exit(1)

print(f"\n📂  Loading data from final_payload.json ...")
D = json.load(open(PAYLOAD))

print(f"    ✅  {D['kpis']['unique_people']} unique people, "
      f"{D['kpis']['unique_meetings']} meetings, "
      f"{D['kpis']['total_records']} records")

# ── Helper: series badge tags ────────────────────────────────
def series_tags(series_str):
    colors = {
        'CME': '#4f86c6',
        'Grand Rounds': '#e07b39',
        'Research': '#5aab61',
        'Lecture': '#a855c8',
        'Conference': '#c84a4a',
        'Workshop': '#d4a017',
        'Seminar': '#2aacbb',
    }
    tags = []
    for s in str(series_str).split(' | '):
        s = s.strip()
        if not s:
            continue
        col = '#888'
        for k, v in colors.items():
            if k.lower() in s.lower():
                col = v
                break
        tags.append(
            f'<span class="stag" style="background:{col}22;'
            f'color:{col};border:1px solid {col}44">{s}</span>'
        )
    return ''.join(tags)

# ── Helper: directory table rows ────────────────────────────
def dir_rows():
    def format_name_for_ui(n):
        n = re.sub(r'^Dr\.?\s+', '', str(n).strip(), flags=re.IGNORECASE).strip()
        parts = n.split(' ')
        if len(parts) >= 2:
            return f"{parts[-1]}, " + " ".join(parts[:-1])
        return n

    rows = []
    for p in D['table']:
        deg   = f'<span class="deg-inline">{p["degree"]}</span>' if p.get('degree') else ''
        dept  = p.get('dept',  '') or ''
        divis = p.get('division', '') or ''
        title = p.get('admin_title', '') or ''
        pos   = p.get('pos',   '') or ''
        rank  = p.get('rank',  '') or ''
        email = p.get('email', '') or ''
        sess  = p.get('session_count', 0)
        c_min = p.get('cumulative_minutes', 0)
        ser   = series_tags(p.get('series', ''))
        first = p.get('first_seen', '')[:7]
        last  = p.get('last_seen',  '')[:7]
        ui_name = format_name_for_ui(p["name"])
        link = f'<a href="#" onclick="drilldownToPerson(\\\'{p["name"]}\\\'); return false;" class="name-cell" style="color:var(--c1d);text-decoration:none;border-bottom:1px dashed var(--c1)">{ui_name}</a>'
        
        rows.append(
            f'<tr data-dept="{dept}" data-pos="{pos}" '
            f'data-rank="{rank}" data-sessions="{sess}">\n'
            f'  <td>{link}{deg}</td>\n'
            f'  <td>{title}</td>\n'
            f'  <td>{dept}</td>\n'
            f'  <td>{divis}</td>\n'
            f'  <td>{rank}</td>\n'
            f'  <td>{pos}</td>\n'
            f'  <td>{email}</td>\n'
            f'  <td class="num">{c_min}</td>\n'
            f'  <td class="num">{sess}</td>\n'
            f'  <td>{ser}</td>\n'
            f'  <td>{first}</td>\n'
            f'  <td>{last}</td>\n'
            f'</tr>'
        )
    return '\n'.join(rows)

def top_table_rows():
    # Sort by session count (descending) then duration (descending)
    sorted_p = sorted(D['table'], key=lambda x: (int(x.get('session_count', 0)), int(x.get('cumulative_minutes', 0))), reverse=True)
    top10 = sorted_p[:10]
    rows = []
    for i, p in enumerate(top10):
        ui_name = format_name_for_ui(p["name"])
        link = f'<a href="#" onclick="drilldownToPerson(\\\'{p["name"]}\\\'); return false;" class="name-cell" style="color:var(--c1d);text-decoration:none;border-bottom:1px dashed var(--c1)">{ui_name}</a>'
        
        rows.append(
            f'<tr>\n'
            f'  <td style="font-weight:700; color:var(--c1d)">#{i+1}</td>\n'
            f'  <td>{link}</td>\n'
            f'  <td>{p.get("dept","")}</td>\n'
            f'  <td class="num" style="color:var(--c2d); font-size:1.1rem">{p.get("session_count",0)}</td>\n'
            f'  <td class="num">{p.get("cumulative_minutes",0)}</td>\n'
            f'</tr>'
        )
    return '\n'.join(rows)

# ── Helper: filter dropdowns ─────────────────────────────────
def dept_filter_opts():
    opts = ['<option value="">All Departments</option>']
    for d in sorted(D['dept_list']):
        if d:
            opts.append(f'<option value="{d}">{d}</option>')
    return '\n'.join(opts)

def rank_filter_opts():
    opts = ['<option value="">All Ranks</option>']
    for r in sorted(D['rank_list']):
        if r:
            opts.append(f'<option value="{r}">{r}</option>')
    return '\n'.join(opts)

def person_filter_opts():
    opts = ['<option value="">Search or Select Attendee...</option>']
    for p in sorted(D.get('person_list', [])):
        if p:
            opts.append(f'<option value="{p}">{p}</option>')
    return '\n'.join(opts)

def la_arrays(d):
    return json.dumps(d['labels']), json.dumps(d['values'])

# ── Build replacement map ─────────────────────────────────────
POS_LABELS, POS_DATA = la_arrays(D['positions'])
ETH_LABELS, ETH_DATA = la_arrays(D['ethnicity'])
GEN_LABELS, GEN_DATA = la_arrays(D['gender'])

replacements = {
    '__SERIES_JSON__':        json.dumps(D['series']['labels']),
    '__SERIES_DATA__':        json.dumps(D['series']['values']),
    '__SESSIONS_JSON__':      json.dumps([s['label'][:45] for s in D['sessions']]),
    '__SESSIONS_DATA__':      json.dumps([s['n'] for s in D['sessions']]),
    '__DEPTS_JSON__':         json.dumps(D['depts']['labels']),
    '__DEPTS_DATA__':         json.dumps(D['depts']['values']),
    '__RANKS_JSON__':         json.dumps(D['ranks']['labels']),
    '__RANKS_DATA__':         json.dumps(D['ranks']['values']),
    '__POS_LABELS__':         POS_LABELS,
    '__POS_DATA__':           POS_DATA,
    '__ETH_LABELS__':         ETH_LABELS,
    '__ETH_DATA__':           ETH_DATA,
    '__GEN_LABELS__':         GEN_LABELS,
    '__GEN_DATA__':           GEN_DATA,
    '__KPI_RECORDS__':        str(D['kpis']['total_records']),
    '__KPI_PEOPLE__':         str(D['kpis']['unique_people']),
    '__KPI_MEETINGS__':       str(D['kpis']['unique_meetings']),
    '__KPI_DEPT__':           str(D['kpis']['dept_pct']),
    '__DIR_ROWS__':           dir_rows(),
    '__TOP_TABLE_ROWS__':     top_table_rows(),
    '__DEPT_OPTS__':          dept_filter_opts(),
    '__RANK_OPTS__':          rank_filter_opts(),
    '__PERSON_OPTS__':        person_filter_opts(),
    '__SERIES_AVG_JSON__':    json.dumps(D['series_avg']['labels']),
    '__SERIES_AVG_DATA__':    json.dumps(D['series_avg']['values']),
    '__SERIES_AVG_SESS__':    json.dumps(D['series_avg']['sessions']),
    '__SERIES_AVG_TOTALS__':  json.dumps(D['series_avg']['totals']),
    '__SESSIONS_BY_SERIES__': json.dumps(D['sessions_by_series']),
    '__SCATTER_PEOPLE__':     json.dumps(D['scatter_people']),
    '__DEPT_BUBBLES__':       json.dumps(D['dept_bubbles']),
    '__SERIES_REACH_JSON__':  json.dumps(list(D['series_reach'].keys())),
    '__SERIES_REACH_DATA__':  json.dumps(list(D['series_reach'].values())),
    '__LOYALTY_JSON__':       json.dumps(D['loyalty']['labels']),
    '__LOYALTY_DATA__':       json.dumps(D['loyalty']['values']),
    '__TIMELINE_JSON__':      json.dumps([s['label'] for s in D['timeline']]),
    '__TIMELINE_DATA__':      json.dumps([s['n'] for s in D['timeline']]),
    '__TIMELINE_DATES__':     json.dumps([s['date'] for s in D['timeline']]),
    '__TIMELINE_SERIES__':    json.dumps([s.get('series', '') for s in D['timeline']]),
    '__DEPT_SERIES_MAP__':    json.dumps(D.get('dept_series', {})),
    '__PERSON_SERIES_MAP__':  json.dumps(D.get('person_series', {})),
    '__PERSON_DATES_MAP__':   json.dumps(D.get('person_dates', {})),
}

# Advanced KPIs (Calculated on the fly from payload data)
total_mins = sum([int(p.get('cumulative_minutes', 0)) for p in D['table']])
avg_dur = round(total_mins / max(1, D['kpis']['total_records']))
replacements['__KPI_AVG_DUR__'] = f"{avg_dur}m"

# Loyalty values [1 session, 2-3 sessions, 4-6 sessions, 7+ sessions]
if sum(D['loyalty']['values']) > 0:
    repeat_attendees = sum(D['loyalty']['values'][1:])
    repeat_pct = round((repeat_attendees / D['kpis']['unique_people']) * 100)
else:
    repeat_pct = 0
replacements['__KPI_REPEAT__'] = f"{repeat_pct}%"

# ── Apply template ────────────────────────────────────────────
print(f"\n📋  Applying template ...")
HTML = open(TEMPLATE).read()

for key, val in replacements.items():
    HTML = HTML.replace(key, val)

# Check for any missed placeholders
missed = [k for k in replacements if k in HTML]
if missed:
    print(f"    ⚠️  Unfilled placeholders: {missed}")
else:
    print(f"    ✅  All {len(replacements)} placeholders filled")

# ── Write output ──────────────────────────────────────────────
with open(OUTPUT, 'w', encoding='utf-8') as f:
    f.write(HTML)

size_kb = os.path.getsize(OUTPUT) / 1024
print(f"\n✅  Dashboard saved → hucm_ofd_dashboard.html  ({size_kb:.0f} KB)")
print(f"    Generated: {datetime.now().strftime('%B %d, %Y at %I:%M %p')}")
print(f"\n💡  To update next time:")
print(f"    1. Replace final_payload.json with your new data")
print(f"    2. Run: python3 update_dashboard.py")
print(f"    3. Upload hucm_ofd_dashboard.html to Netlify")
print("=" * 55)
